name: "Deploy Action"
description: "Deploys code to AWS"

inputs:
  ecr-repository:
    description: "AWS ECR repository name"
    required: true
  task-definition:
    description: "Task definition name"
    required: true
  container-name:
    description: "Name of the container in task definition"
    required: true
  service:
    description: "Service name"
    required: true
  cluster:
    description: "Cluster name"
    required: true
  image-tag:
    description: "Image tag"
    required: true
  github-scope:
    description: "GitHub scope name for creating .npmrc"
    required: true
  github-token:
    description: "GitHub package token"
    required: true
  aws-access-key-id:
    description: "AWS access key ID"
    required: true
  aws-secret-access-key:
    description: "AWS secret access key"
    required: true
  aws-region:
    description: "AWS region"
    required: true
  build-app:
    description: "Should build app by running yarn build"
    default: false
  payload-secret: # ✅ Added secret as an input
    description: "Payload secret key"
    required: true
  database-uri: # ✅ Added secret as an input
    description: "Database URI"
    required: true

runs:
  using: "composite"
  steps:
    - name: Create .npmrc
      run: |
        echo "//npm.pkg.github.com/:_authToken=${{ inputs.github-token }}" >> ~/.npmrc
        echo "${{ inputs.github-scope }}:registry=https://npm.pkg.github.com" >> ~/.npmrc
      shell: bash

    - name: Running package install
      run: yarn
      shell: bash

    - name: Build the app if requested
      run: |
        if [[ "${{ inputs.build-app }}" == "true" ]]; then
          yarn build
        fi
      shell: bash

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1-node16
      with:
        aws-access-key-id: ${{ inputs.aws-access-key-id }}
        aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
        aws-region: ${{ inputs.aws-region }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: ${{ inputs.ecr-repository }}
        IMAGE_TAG: ${{ inputs.image-tag }}
        GITHUB_TOKEN: ${{ inputs.github-token }}
        PAYLOAD_SECRET: ${{ secrets.PAYLOAD_SECRET }}
        DATABASE_URI: ${{ secrets.DATABASE_URI }}
      run: |
        docker buildx create --use
        docker buildx build \
          --platform linux/amd64,linux/arm64 \
          --build-arg PAYLOAD_SECRET=$PAYLOAD_SECRET \
          --build-arg DATABASE_URI=$DATABASE_URI \
          -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG \
          --build-arg PKG_AUTH_TOKEN=$GITHUB_TOKEN .

        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
      shell: bash

    - name: Download task-definition
      run: |
        aws ecs describe-task-definition --task-definition ${{ inputs.task-definition }} --query taskDefinition > task-definition.json
      shell: bash

    - name: Create task definition revision
      id: render-image
      uses: aws-actions/amazon-ecs-render-task-definition@v1
      with:
        task-definition: task-definition.json
        container-name: ${{ inputs.container-name }}
        image: ${{ steps.login-ecr.outputs.registry }}/${{ inputs.ecr-repository }}:${{ inputs.image-tag }}

    - name: Deploy task definition to service
      uses: aws-actions/amazon-ecs-deploy-task-definition@v2
      with:
        task-definition: ${{ steps.render-image.outputs.task-definition }}
        service: ${{ inputs.service }}
        cluster: ${{ inputs.cluster }}
