name: "Deploy Action"
description: "Deploys code to aws"
inputs:
  ecr-repository:
    description: "Aws ECR repository name"
    required: true
  task-definition:
    description: "Task definition name"
    required: true
  container-name:
    description: "Name of the container in task definition"
    required: true
  service:
    description: "Service name"
    required: true
  cluster:
    description: "Cluster name"
    required: true
  github-scope:
    description: "Gihub scope name for creating .npmrc"
    required: true

runs:
  using: "composite"
  steps:
    - name: Create .npmrc
      run: |
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.PKG_AUTH_TOKEN }}" >> ~/.npmrc
          echo "${{ github-scope }}:registry=https://npm.pkg.github.com" >> ~/.npmrc
    # Runs a packages install
    - name: Running package install
      run: yarn

    # Configure AWS credentials
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    # Login to ECR
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    # Build docker image and push it to ECR
    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: ${{ ecr-repository }}
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

    # Download task-dfinition json file
    - name: Download task-definition
      run: |
        aws ecs describe-task-definition --task-definition ${{ task-definition }} --query taskDefinition > task-definition.json

    # Replace image on task definition
    - name: Create task definition revision
      id: render-image
      uses: aws-actions/amazon-ecs-render-task-definition@v1
      with:
        task-definition: task-definition.json
        container-name: ${{ container-name }}
        image: ${{ steps.login-ecr.outputs.registry }}/${{ ecr-repository }}:${{ github.sha }}

    # Deploy task definition
    - name: Deploy task definition to service
      uses: aws-actions/amazon-ecs-deploy-task-definition@v1
      with:
        task-defintion: ${{ steps.render-image.outputs.task-definition }}
        service: ${{ service }}
        cluster: ${{ cluster }}
